#!/usr/bin/env bash
# Source this after activating .venv on every new terminal.
export ECODEP_CONTAINER_RUNTIME=native
export ECODEP_ATTENTION_GPUS="${ECODEP_ATTENTION_GPUS:-0,1}"
export ECODEP_EXPERT_GPUS="${ECODEP_EXPERT_GPUS:-2,3}"
export ECODEP_CLOCK_URL="${ECODEP_CLOCK_URL:-http://127.0.0.1:9096}"
export ECODEP_ATTENTION_CLOCK_URL="$ECODEP_CLOCK_URL"
export ECODEP_EXPERT_CLOCK_URL="$ECODEP_CLOCK_URL"
export ECODEP_GPU_WAIT_TIMEOUT_S="${ECODEP_GPU_WAIT_TIMEOUT_S:-86400}"
export ECODEP_GPU_STABLE_FOR_S="${ECODEP_GPU_STABLE_FOR_S:-120}"
export ECODEP_MINIMUM_FREE_GIB="${ECODEP_MINIMUM_FREE_GIB:-79}"
export PYTHONDONTWRITEBYTECODE=1
export VLLM_USE_V2_MODEL_RUNNER=0
export PYTHONUNBUFFERED=1
unset CUDA_VISIBLE_DEVICES

export ECODEP_API_PORT="${ECODEP_API_PORT:-18000}"
export ECODEP_EXPERT_API_PORT="${ECODEP_EXPERT_API_PORT:-18001}"
export ECODEP_AFD_PORT="${ECODEP_AFD_PORT:-16239}"
export ECODEP_DP_RPC_BASE_PORT="${ECODEP_DP_RPC_BASE_PORT:-29550}"
